apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-db-init
data:
  prep.sql: {{ include "kea-db-prep" . | b64enc }}
  kea-admin-init.sh: {{ include "kea-admin-dbinit" . | b64enc }}
  
  