apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-config
  labels:
    {{- include "kea4.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
data:
  dhcp4-primary.conf: {{ include "kea4-config" (dict "Release" .Release "Subcharts" .Subcharts "Values" .Values "role" "primary") | b64enc }}
  dhcp4-standby.conf: {{ include "kea4-config" (dict "Release" .Release "Subcharts" .Subcharts "Values" .Values "role" "standby") | b64enc }}
  ctrl-agent.conf: {{ include "kea-ctrl-agent-config" . | b64enc }}
