apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: stork-config
  labels:
    {{- include "kea4.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
data:
  agent-credentials.json: {{ include "stork-agent-credentials" . | b64enc }}
  agent.env: {{ include "stork-agent-env" . | b64enc }}
  server.env: {{ include "stork-server-env" . | b64enc }}
