apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: pgpool-users
  labels:
    {{- include "kea4.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
data:
  pgp-users.sh: {{ include "pgpool-add-users" . | b64enc }}
