apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-config
  labels:
    {{- include "kea4.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
data:
  dhcp4.conf: {{ include "kea4-config" . | b64enc }}
  ctrl-agent.conf: {{ include "kea-ctrl-agent-config" . | b64enc }}
{{ ( include "kea-ctrl-agent.gen-certs" . ) | indent 2 }}
