apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-db-init
  labels:
    {{- include "kea4.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
data:
  DB_HOST: {{ include "pgpool-fqdn" . | b64enc }}
  CONFIG_DB_USER: {{ .Values.configDB.user | b64enc }}
  CONFIG_DB_PASSWORD: {{ .Values.configDB.password | b64enc }}
  PRIMARY_CONFIG_DB_NAME: {{ .Values.configDB.primary | b64enc }}
  STANDBY_CONFIG_DB_NAME: {{ .Values.configDB.standby | b64enc }}
  STORK_DB_USER: {{ .Values.storkDB.user | b64enc }}
  STORK_DB_PASSWORD: {{ .Values.storkDB.password | b64enc }}
  STORK_DB_NAME: {{ .Values.storkDB.name | b64enc }}
