apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-db-init
  labels:
    {{- include "kea4.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
data:
  kea-admin-init.sh: {{ include "kea-admin-dbinit" . | b64enc }}
