apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: ctrl
  labels:
    {{- include "kea4.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.agentPort }}
      protocol: TCP
      name: ctrl-agent
  selector:
    {{- include "kea4.selectorLabels" . | nindent 4 }}
