apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "kea4.fullname" . }}
  labels:
    {{- include "kea4.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.dhcpPort }}
      protocol: UDP
      name: dhcp
  selector:
    {{- include "kea4.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "kea4.fullname" . }}-agent
  labels:
    {{- include "kea4.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.agentPort }}
      protocol: TCP
      name: ctrl-agent
  selector:
    {{- include "kea4.selectorLabels" . | nindent 4 }}
